
POST http://localhost:5400/user/register
Content-Type: application/json

{
    "username": "Mwaniki Jonathan",
    "email": "mwaniki@gmail.com",
    "password": "@Mwaniki123"

} 

###
GET http://localhost:5400/user/
Content-Type: application/json